package fr.uptrash.fuckupplanning.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFF4554BC)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFF8493FF)
private val onPrimaryContainerLight = Color(0xFF112390)
private val secondaryLight = Color(0xFF565C85)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFCACEFE)
private val onSecondaryContainerLight = Color(0xFF525780)
private val tertiaryLight = Color(0xFF933C8C)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFD979CE)
private val onTertiaryContainerLight = Color(0xFF5F055D)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF93000A)
private val backgroundLight = Color(0xFFFBF8FF)
private val onBackgroundLight = Color(0xFF1B1B22)
private val surfaceLight = Color(0xFFFBF8FF)
private val onSurfaceLight = Color(0xFF1B1B22)
private val surfaceVariantLight = Color(0xFFE2E1F1)
private val onSurfaceVariantLight = Color(0xFF454653)
private val outlineLight = Color(0xFF767684)
private val outlineVariantLight = Color(0xFFC6C5D5)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF303037)
private val inverseOnSurfaceLight = Color(0xFFF2EFF9)
private val inversePrimaryLight = Color(0xFFBCC3FF)
private val surfaceDimLight = Color(0xFFDBD9E2)
private val surfaceBrightLight = Color(0xFFFBF8FF)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFF5F2FC)
private val surfaceContainerLight = Color(0xFFEFEDF6)
private val surfaceContainerHighLight = Color(0xFFE9E7F0)
private val surfaceContainerHighestLight = Color(0xFFE3E1EB)

private val primaryDark = Color(0xFFBCC3FF)
private val onPrimaryDark = Color(0xFF0C1F8D)
private val primaryContainerDark = Color(0xFF8493FF)
private val onPrimaryContainerDark = Color(0xFF112390)
private val secondaryDark = Color(0xFFBFC3F3)
private val onSecondaryDark = Color(0xFF282D54)
private val secondaryContainerDark = Color(0xFF3F446C)
private val onSecondaryContainerDark = Color(0xFFADB2E1)
private val tertiaryDark = Color(0xFFFFABF2)
private val onTertiaryDark = Color(0xFF5B015A)
private val tertiaryContainerDark = Color(0xFFD979CE)
private val onTertiaryContainerDark = Color(0xFF5F055D)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF121319)
private val onBackgroundDark = Color(0xFFE3E1EB)
private val surfaceDark = Color(0xFF121319)
private val onSurfaceDark = Color(0xFFE3E1EB)
private val surfaceVariantDark = Color(0xFF454653)
private val onSurfaceVariantDark = Color(0xFFC6C5D5)
private val outlineDark = Color(0xFF8F8F9E)
private val outlineVariantDark = Color(0xFF454653)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFE3E1EB)
private val inverseOnSurfaceDark = Color(0xFF303037)
private val inversePrimaryDark = Color(0xFF4554BC)
private val surfaceDimDark = Color(0xFF121319)
private val surfaceBrightDark = Color(0xFF383940)
private val surfaceContainerLowestDark = Color(0xFF0D0E14)
private val surfaceContainerLowDark = Color(0xFF1B1B22)
private val surfaceContainerDark = Color(0xFF1F1F26)
private val surfaceContainerHighDark = Color(0xFF292930)
private val surfaceContainerHighestDark = Color(0xFF34343B)

val blueLightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val blueDarkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)
