package fr.uptrash.fuckupplanning.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFFAF2362)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFFF64A0)
private val onPrimaryContainerLight = Color(0xFF6A0036)
private val secondaryLight = Color(0xFF904760)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFFFA4C0)
private val onSecondaryContainerLight = Color(0xFF7B364F)
private val tertiaryLight = Color(0xFFA23F00)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFFE7020)
private val onTertiaryContainerLight = Color(0xFF5B2000)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF93000A)
private val backgroundLight = Color(0xFFFFF8F8)
private val onBackgroundLight = Color(0xFF25181C)
private val surfaceLight = Color(0xFFFFF8F8)
private val onSurfaceLight = Color(0xFF25181C)
private val surfaceVariantLight = Color(0xFFFBDAE2)
private val onSurfaceVariantLight = Color(0xFF574147)
private val outlineLight = Color(0xFF8A7077)
private val outlineVariantLight = Color(0xFFDEBFC6)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF3B2D30)
private val inverseOnSurfaceLight = Color(0xFFFFECF0)
private val inversePrimaryLight = Color(0xFFFFB1C8)
private val surfaceDimLight = Color(0xFFEBD4D9)
private val surfaceBrightLight = Color(0xFFFFF8F8)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFFFF0F2)
private val surfaceContainerLight = Color(0xFFFFE8ED)
private val surfaceContainerHighLight = Color(0xFFFAE2E7)
private val surfaceContainerHighestLight = Color(0xFFF4DDE2)

private val primaryDark = Color(0xFFFFB1C8)
private val onPrimaryDark = Color(0xFF650033)
private val primaryContainerDark = Color(0xFFFF64A0)
private val onPrimaryContainerDark = Color(0xFF6A0036)
private val secondaryDark = Color(0xFFFFB1C8)
private val onSecondaryDark = Color(0xFF581932)
private val secondaryContainerDark = Color(0xFF76324B)
private val onSecondaryContainerDark = Color(0xFFF99EBA)
private val tertiaryDark = Color(0xFFFFB695)
private val onTertiaryDark = Color(0xFF571F00)
private val tertiaryContainerDark = Color(0xFFFE7020)
private val onTertiaryContainerDark = Color(0xFF5B2000)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF1C1014)
private val onBackgroundDark = Color(0xFFF4DDE2)
private val surfaceDark = Color(0xFF1C1014)
private val onSurfaceDark = Color(0xFFF4DDE2)
private val surfaceVariantDark = Color(0xFF574147)
private val onSurfaceVariantDark = Color(0xFFDEBFC6)
private val outlineDark = Color(0xFFA58A91)
private val outlineVariantDark = Color(0xFF574147)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFF4DDE2)
private val inverseOnSurfaceDark = Color(0xFF3B2D30)
private val inversePrimaryDark = Color(0xFFAF2362)
private val surfaceDimDark = Color(0xFF1C1014)
private val surfaceBrightDark = Color(0xFF443539)
private val surfaceContainerLowestDark = Color(0xFF160B0E)
private val surfaceContainerLowDark = Color(0xFF25181C)
private val surfaceContainerDark = Color(0xFF291C20)
private val surfaceContainerHighDark = Color(0xFF34262A)
private val surfaceContainerHighestDark = Color(0xFF3F3135)

val pinkLightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val pinkDarkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)